version: '3.7'
services:

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        environment:
            PHP_HOST: php
            PHP_PORT: 9000

    php:
        image: php:8.1-fpm-alpine3.16
        volumes:
            - ./:/app
        working_dir: /app

    composer:
        image: composer:2.0.14
        volumes:
            - ./:/app
        working_dir: /app

