version: '3.7'
services:
    php:
        image: php:8.1-fpm-alpine3.16
        volumes:
            - ./:/app
        working_dir: /app

    composer:
        image: composer:2.0.14
        volumes:
            - ./:/app
        working_dir: /app

